---
title: "Steigerwald"
author: "Lallu Nikerthil Prathapan"
date: "11/8/2021"
output: html_document
---
install.packages("RCurl")
```{r df,echo = TRUE}
library(RCurl)
df <-read.csv("https://raw.githubusercontent.com/wegmann/R_data/master/Steigerwald_sample_points_all_data_subset_withNames.csv")
df
```

```{r df,echo = TRUE}
head(df)
tail(df)
summary(df)
```
```{r df,echo = TRUE}
```


```{r df,echo = TRUE}
plot(df)
```


```{r df,echo = TRUE}
str(df)
```
```{r df, echo = TRUE}
names(df)#provides the 1st raw headings
dim(df)#provides the dimension of data frame
```


```{r df, echo = TRUE}
df[,3:12]#gives just the s3 bands
```


```{r df, echo = TRUE}
df$LUCAS_LC

```
```{r df, echo=TRUE}
df[c(3,14)]# selects LUCAS_LC and SRTM data
x2<-df[length(df)-2]
x2

```

```{r x2, echo=TRUE}
x2<-df[(length(df)-2)]
x2#prints second last column

```


```{r df,echo = TRUE}
df[1:10,]#select all columns but just 10 rows
```



```{r rt,echo = TRUE}
rt<-df[c(14,34)]
plot(rt)
```
```{r df,echo = TRUE}

#Plots SRTM for predefined value of NDVI
df$L8.ndvi>0.6
d2<-(df$L8.ndvi)>0.6
d2
v<-df[d2,"L8.ndvi"]
v
u<-df[d2,"SRTM"]
u
plot(u,v)

```
``````{r df,echo = TRUE}
#Create a new dataframe with all entries but only corressponding NDVI values abouve 0.5

ndvinw<-df$L8.ndvi>0.5
df[ndvinw,]
nw_df<-df[ndvinw,]
nw_df
str(nw_df)
summary(nw_df)


```
```{r}

```


```{r df,echo=TRUE}
#select data where LC values below x or above y
k<-df$X.1
k
m<-df$LUCAS_LC<k
l<-df$X
l
n<-df$LUCAS_LC>l
n
r<-df[(l|n),]
str(r)
summary(r)
r


```

